name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       vctl build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
       vctl run ghcr.io/deselikem/hello-docker-gcr-demo:latest
       vctl push ghcr.io/deselikem/hello-docker-gcr-demo:latest